from gurobipy import *
m = read('openStarNet_3-bus.lp')
m.printStats()
m.setParam('Method'   ,2)
m.setParam('Crossover',0)
m.setParam('OutputFlag', 1)
m.setParam('LogToConsole', 1)
m.setParam('NumericFocus', 3)
m.setParam('IISMethod', 0)
m.setParam('BarHomogeneous', 1)
m.setParam('NonConvex', 2)
# m.setParam('FeasRelaxS', 0)
# m.write('p2.lp')
# m=m.presolve()
# m.write('pp_PS.lp')
# m.feasRelaxS(2, False, False, True)
# m.optimize()
# m.printQuality()
# print(m.KappaExact)
# m.optimize()
m.computeIIS()
m.write('openStarNet_3-bus.ilp')
