#!/bin/bash -l


#SBATCH --cluster="genius"
#SBATCH --job-name="9n_full_MILP"
#SBATCH --nodes="1"
#SBATCH --mail-user="kristof.phillips@kuleuven.be"
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --time="72:00:00"
#SBATCH --ntasks-per-node="36"
#SBATCH --account="lp_elect_gen_modeling"
#SBATCH --partition="batch"
      
source activate Jr23
echo "Activation OK"
cd $VSC_DATA/JointResearch/05.Models/06.Benchmarking/A.The_full_year_MILP

echo "Starting runs"

python oSN_Main_v2.py
