#!/bin/bash -l


#SBATCH --cluster="genius"
#SBATCH --job-name="3-bus_12w"
#SBATCH --nodes="1"
#SBATCH --mail-user="kristof.phillips@kuleuven.be"
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --time="6:00:00"
#SBATCH --ntasks-per-node="36"
#SBATCH --account="lp_elect_gen_modeling"
#SBATCH --partition="batch"
      
source activate Jr23
echo "Activation OK"
cd $VSC_DATA/JointResearch/05.Models/06.Benchmarking/C.The_1st_week_per_month

echo "Starting runs"

python TrainingDataGenerator_v2.py --case 3-bus
