#!/bin/bash -l


#SBATCH --cluster="genius"
#SBATCH --job-name="12w_DC_RTS24"
#SBATCH --nodes="1"
#SBATCH --mail-user="kristof.phillips@kuleuven.be"
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --time="48:00:00"
#SBATCH --ntasks-per-node="36"
#SBATCH --account="lp_elect_gen_modeling"
#SBATCH --partition="batch"
      
source activate Jr23
echo "Activation OK"
cd $VSC_DATA/JointResearch/05.Models/06.Benchmarking/C.The_1st_week_per_month

echo "Starting runs"

python TrainingDataGenerator_DCOPF.py --case RTS24

# cp 9n/openStarNet_9n.log 9n/3.Out/
