# TOML file configuration

# name of the case 
dataName = "Demand_RTSGMLC.txt"

# column of the date
# if it does not exist, put "null"
dateName = "null"

# variables to compute the DFT
variables = ['Streamflows_std_norm']

# steps in
n_steps_in = 168

# steps out
n_steps_out = 24

# data trainning fraction
train_fraction = 0.80

# multi-step
multistep = 0

