# TOML file configuration

# name of the case 
dataName = "Streamflows_annual.txt"

# column of the date
# if it does not exist, put "null"
dateName = "null"

# variables to compute the DFT
variables = ['Streamflows_std_norm']

# steps in
n_steps_in = 1

# steps out
n_steps_out = 1

# data trainning fraction
train_fraction = 0.85

# multi-step
multistep = 1

