#!/bin/bash -l


#SBATCH --cluster="genius"
#SBATCH --job-name="RTS24_NN_OC_fy_1"
#SBATCH --nodes="1"
#SBATCH --mail-user="kristof.phillips@kuleuven.be"
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --time="24:00:00"
#SBATCH --ntasks-per-node="36"
#SBATCH --account="lp_elect_gen_modeling"
#SBATCH --partition="batch"
      
source activate Jr23
echo "Activation OK"
cd $VSC_DATA/JointResearch/05.Models/06.Benchmarking/F.Representative_days_based_on_Line_Benefit_NN_OC_fy_1

echo "Starting runs"

python oSN_Main_v2.py --case RTS24_ByStages

# cp RTS24/openS